/**
 * Browser translation of the official vaderSentiment 3.3.2 Python algorithm.
 * Original: C.J. Hutto; MIT license in vendor/VADER-LICENSE.txt.
 * https://github.com/cjhutto/vaderSentiment
 * Hutto & Gilbert (ICWSM 2014). No kitchen lexicon or sentiment overrides.
 * Versioned tables and official-Python differential fixtures are generated by
 * scripts/export-vader-reference.py. Scores are raw, uncalibrated sentiment.
 */
import data from './vendor/vader-data.json';

export interface VaderSentimentScores {
  neg: number;
  neu: number;
  pos: number;
  compound: number;
}

export const VADER_IMPLEMENTATION = 'vaderSentiment-3.3.2-browser-parity-v1';
const lexicon: Record<string, number> = data.lexicon;
const emojis: Record<string, string> = data.emojis;
const boosters: Record<string, number> = data.boosters;
const specialCases: Record<string, number> = data.specialCases;
const negators = new Set(data.negators);
const N_SCALAR = -0.74;
const C_INCR = 0.733;
const has = (object: object, key: string): boolean => Object.hasOwn(object, key);
const isUpper = (word: string): boolean => word !== word.toLowerCase() && word === word.toUpperCase();
const negated = (word: string): boolean => negators.has(word) || word.includes("n't");

function round(value: number, places: number): number {
  const scale = 10 ** places;
  const scaled = Math.abs(value) * scale;
  if (scaled % 1 === 0.5) return Math.sign(value) * (Math.round(scaled / 2) * 2) / scale;
  return Number(value.toFixed(places));
}

function expandEmoji(text: string): string {
  let output = '';
  let previousSpace = true;
  for (const character of text) {
    if (has(emojis, character)) {
      if (!previousSpace) output += ' ';
      output += emojis[character];
      previousSpace = false;
    } else {
      output += character;
      previousSpace = character === ' ';
    }
  }
  return output.trim();
}

function tokens(text: string): string[] {
  return text ? text.split(/\s+/u).map((token) => {
    // Python string.punctuation; preserve short tokens that may be emoticons.
    const stripped = token.replace(/^[!"#$%&'()*+,\-./:;<=>?@[\]\\^_`{|}~]+|[!"#$%&'()*+,\-./:;<=>?@[\]\\^_`{|}~]+$/gu, '');
    return stripped.length <= 2 ? token : stripped;
  }) : [];
}

function negationCheck(valence: number, words: string[], distance: number, index: number): number {
  if (distance === 1) {
    if (words[index - 2] === 'never' && ['so', 'this'].includes(words[index - 1])) return valence * 1.25;
    if (words[index - 2] === 'without' && words[index - 1] === 'doubt') return valence;
  }
  if (distance === 2) {
    // Keep the reference implementation's operator precedence for reproducibility.
    if ((words[index - 3] === 'never' && ['so', 'this'].includes(words[index - 2])) ||
        ['so', 'this'].includes(words[index - 1])) return valence * 1.25;
    if (words[index - 3] === 'without' && [words[index - 2], words[index - 1]].includes('doubt')) return valence;
  }
  return negated(words[index - distance - 1]) ? valence * N_SCALAR : valence;
}

function idiomsCheck(valence: number, words: string[], index: number): number {
  const phrase = (from: number, to: number): string => words.slice(from, to + 1).join(' ');
  const sequences = [phrase(index - 1, index), phrase(index - 2, index),
    phrase(index - 2, index - 1), phrase(index - 3, index - 1), phrase(index - 3, index - 2)];
  for (const sequence of sequences) {
    if (has(specialCases, sequence)) { valence = specialCases[sequence]; break; }
  }
  for (const length of [1, 2]) {
    if (words.length - 1 >= index + length) {
      const sequence = phrase(index, index + length);
      if (has(specialCases, sequence)) valence = specialCases[sequence];
    }
  }
  for (const sequence of [sequences[3], sequences[4], sequences[2]]) {
    if (has(boosters, sequence)) valence += boosters[sequence];
  }
  return valence;
}

function wordValence(original: string[], words: string[], index: number, capitalDifference: boolean): number {
  const word = words[index];
  if (has(boosters, word) || (word === 'kind' && words[index + 1] === 'of') || !has(lexicon, word)) return 0;
  let valence = lexicon[word];
  if (word === 'no' && index !== words.length - 1 && has(lexicon, words[index + 1])) valence = 0;
  if ((index > 0 && words[index - 1] === 'no') || (index > 1 && words[index - 2] === 'no') ||
      (index > 2 && words[index - 3] === 'no' && ['or', 'nor'].includes(words[index - 1]))) {
    valence = lexicon[word] * N_SCALAR;
  }
  if (isUpper(original[index]) && capitalDifference) valence += valence > 0 ? C_INCR : -C_INCR;
  for (let distance = 0; distance < 3; distance += 1) {
    if (index <= distance || has(lexicon, words[index - distance - 1])) continue;
    const preceding = words[index - distance - 1];
    let scalar = 0;
    if (has(boosters, preceding)) {
      scalar = boosters[preceding] * (valence < 0 ? -1 : 1);
      if (capitalDifference && isUpper(original[index - distance - 1])) scalar += valence > 0 ? C_INCR : -C_INCR;
    }
    if (distance === 1 && scalar !== 0) scalar *= 0.95;
    if (distance === 2 && scalar !== 0) scalar *= 0.9;
    valence += scalar;
    valence = negationCheck(valence, words, distance, index);
    if (distance === 2) valence = idiomsCheck(valence, words, index);
  }
  if (index > 0 && words[index - 1] === 'least' && !has(lexicon, words[index - 1])) {
    if (index === 1 || !['at', 'very'].includes(words[index - 2])) valence *= N_SCALAR;
  }
  return valence;
}

/** Official raw VADER polarity scores; directive polarity is handled elsewhere. */
export function scoreVaderSentiment(input: string): VaderSentimentScores {
  const text = expandEmoji(input);
  const original = tokens(text);
  const words = original.map((word) => word.toLowerCase());
  const capitalCount = original.filter(isUpper).length;
  const capitalDifference = capitalCount > 0 && capitalCount < original.length;
  const sentiments = words.map((_, index) => wordValence(original, words, index, capitalDifference));
  if (!sentiments.length) return { neg: 0, neu: 0, pos: 0, compound: 0 };
  const but = words.indexOf('but');
  if (but !== -1) {
    // Python 3.3.2 uses value-index lookup while modifying the same list.
    for (let pass = 0; pass < sentiments.length; pass += 1) {
      const value = sentiments[pass];
      const index = sentiments.indexOf(value);
      if (index < but) sentiments[index] = value * 0.5;
      else if (index > but) sentiments[index] = value * 1.5;
    }
  }
  const questionCount = (text.match(/\?/gu) ?? []).length;
  const punctuation = Math.min((text.match(/!/gu) ?? []).length, 4) * 0.292 +
    (questionCount > 3 ? 0.96 : questionCount > 1 ? questionCount * 0.18 : 0);
  let sum = sentiments.reduce((total, value) => total + value, 0);
  if (sum > 0) sum += punctuation;
  else if (sum < 0) sum -= punctuation;
  const compound = sum / Math.sqrt(sum * sum + 15);
  let positive = 0;
  let negative = 0;
  let neutral = 0;
  for (const value of sentiments) {
    if (value > 0) positive += value + 1;
    else if (value < 0) negative += value - 1;
    else neutral += 1;
  }
  if (positive > Math.abs(negative)) positive += punctuation;
  else if (positive < Math.abs(negative)) negative -= punctuation;
  const total = positive + Math.abs(negative) + neutral;
  return { neg: round(Math.abs(negative / total), 3), neu: round(neutral / total, 3),
    pos: round(positive / total, 3), compound: round(compound, 4) };
}
