[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "overcooked_ai"
version = "2.0.0"
description = "Cooperative multi-agent environment based on Overcooked"
readme = "README.md"
requires-python = ">=3.10,<3.11"
license = { file = "LICENSE" }
authors = [{ name = "Micah Carroll", email = "mdc@berkeley.edu" }]
urls = { homepage = "https://github.com/HumanCompatibleAI/overcooked_ai" }
keywords = ["Overcooked", "AI", "Reinforcement Learning"]
dependencies = [
    "dill",
    "dm-tree",
    "GitPython",
    "gym",
    "gymnasium",
    "ipywidgets",
    "lz4",
    "numpy>=1.23,<1.24",
    "opencv-python",
    "pygame",
    "ray[rllib,tune]==2.2",
    "sacred",
    "scipy",
    "setuptools>=77.0.3",
    "tensorflow==2.10.1",
    "tensorflow-io-gcs-filesystem==0.27.0",
    "tqdm",
]

[project.optional-dependencies]
harl = [
    "ipykernel",
    "wandb",
]

[tool.setuptools]
package-dir = { "" = "src" }
packages = { find = { where = ["src"] } }

[tool.setuptools.package-data]
"overcooked_ai_py" = [
    "data/layouts/*.layout",
    "data/planners/*.py",
    "data/graphics/*.png",
    "data/graphics/*.json",
    "data/fonts/*.ttf",
]
"human_aware_rl" = [
    "static/**/*.pickle",
    "static/**/*.csv",
    "ppo/trained_example/*.pkl",
    "ppo/trained_example/*.json",
    "ppo/trained_example/*/.is_checkpoint",
    "ppo/trained_example/*/.tune_metadata",
    "ppo/trained_example/*/checkpoint-500",
]
