"""Additional AI-authored synthetic seeds; no files or participant text are read."""
import json
from pathlib import Path

GROUPS = {
    ('evaluative', 'trajectory'): [
        'I applaud the way you organized that entire shift.',
        'Your last handoff exceeded my expectations.',
        'The way you waited for me was considerate.',
        'You made a mess of that delivery.',
        'That detour was a stroke of genius.',
        'Your coordination left much to be desired.',
        'I was impressed by how smoothly you passed the bowl.',
        'I regret the time we lost during your last trip.',
        'Finishing those orders so early deserves recognition.',
        'The timing of that pickup could not have been better.',
        'Your decision to walk away cost us dearly.',
        'I disapprove of the way you handled the queue.',
        'That whole round was a delight to watch.',
        'You surpassed yourself on the final delivery.',
        'Our teamwork this round was second to none.',
        'That performance was below par.',
        'The effort you put into keeping the aisle clear paid off.',
        'You let us down with that unnecessary stop.',
        'Picking up that spare dish turned out wonderfully.',
        'The delivery you just completed was flawless.',
        'You reacted admirably when I got stuck.',
        'You managed the crowded corner expertly.',
        'We could hardly have asked for a worse handoff.',
        'The careless way you left that onion was frustrating.',
        'What you did with the last bowl was commendable.',
        'I am proud of the progress you made during that round.',
        'Your last turn showed remarkably sound judgment.',
        'I cannot fault your work on that final order.',
        'I am not pleased with how long you stood there.',
        'That pickup was nothing to write home about.',
    ],
    ('evaluative', 'feature'): [
        'A clear work surface makes this kitchen a pleasure to use.',
        'The short path to the hatch is a real asset.',
        'I value easy access to the dish supply.',
        'There is little merit in this cramped arrangement.',
        'The corner nearest the stove is particularly troublesome.',
        'A second place to put bowls would be a blessing.',
        'The wide gap between these worktops is convenient.',
        'This storage arrangement leaves me cold.',
        'The design of the serving station deserves praise.',
        'I have a low opinion of the far cooking station.',
        'Keeping ingredients within reach is beneficial.',
        'This route strikes me as needlessly complicated.',
        'The separate lane for deliveries is a welcome feature.',
        'The lack of counter space is a nuisance.',
        'A long wait for a bowl is unacceptable.',
        'The central stove has an advantage over the distant one.',
        'The kitchen feels much too cluttered for my liking.',
        'I appreciate the extra room beside the serving window.',
        'The distance between the onion supply and the pot is excessive.',
        'I am fond of the little workspace on the upper side.',
    ],
    ('evaluative', 'action'): [
        'You would have done better to collect a bowl instead.',
        'Taking the lower aisle instead would have saved valuable time.',
        'You should have delivered that soup instead of waiting.',
        'It would have been wiser to step aside rather than block me.',
        'Fetching another onion instead would have been the superior choice.',
    ],
    ('imperative', 'action'): [
        'Bring over whichever dish is nearest to you.',
        'Get rid of the ingredient you are holding.',
        'Carry on filling the pot until it has three ingredients.',
        'Let the other cook go through ahead of you.',
        'Put down what you have and come toward me.',
        'See to it that the soup reaches the hatch.',
        'Would you mind passing that onion over here?',
        'Could I ask you to stay beside the empty stove?',
        'I need you to return the spare bowl to the bench.',
        'Make sure to collect the tomato from the lower supply.',
        'Leave enough room for me to get past.',
        'Give me the plate after you finish that delivery.',
        'Hold on to the onion for now.',
        'Turn back before you enter the narrow passage.',
        'Try going around the stove on its other side.',
        'Be careful to keep that hot soup in your hands.',
        'Do not let go of the bowl yet.',
        'Please refrain from picking up another tomato.',
        'I would like you to take over at this pot.',
        'Please go as far as the worktop beside the door.',
        'Continue walking until you reach the dish rack.',
        'Help me by bringing the final ingredient.',
        'Get back to the serving area as soon as you can.',
        'Step out of the space between me and the stove.',
        'Pass along the empty bowl rather than keeping it.',
        'Finish the delivery before collecting anything else.',
        'How about fetching a fresh dish for me?',
        'Would you be able to wait at the upper counter?',
        'You had better move that onion into the pot.',
        'I suggest carrying the soup straight to the customer.',
        'Do me a favor and put that tomato down.',
        'Leave the pot nearest the wall alone.',
        'Go ahead and pick up the bowl on your right.',
        'Please have a go at clearing the center aisle.',
        'Take whichever path gets you to the onion supply.',
        'Start heading toward the serving point.',
        'Keep your hands free until the soup is ready.',
        'Would you please bring me the dish behind you?',
        'Swap places with me at the cooking station.',
        'Stay where I can pass you on the left.',
    ],
    ('descriptive', 'feature'): [
        'The serving point faces the lower wall.',
        'Every available bowl is on the far worktop.',
        'You currently have nothing in either hand.',
        'A pair of tomatoes is sitting beside the stove.',
        'There are four squares from the pot to the window.',
        'Neither cooking station is empty at present.',
        'The opening beside the wall is two tiles wide.',
        'Both cooks are facing the same direction.',
        'What I am carrying is an onion.',
        'The bowl to your left contains cooked soup.',
        'The pot behind me still contains only one ingredient.',
        'One end of the worktop touches the serving station.',
        'Our current order calls for an onion and two tomatoes.',
        'Half of the available counter spaces are occupied.',
        'The stove on the opposite side is unlit.',
        'Your hands are full at the moment.',
        'I am standing directly above the empty dish.',
        'The cook beside you is holding a plate.',
        'Only one of the dishes contains soup.',
        'There are no ingredients on the lower bench.',
        'The two cooking stations share a counter.',
        'Nothing is blocking the tile immediately behind you.',
        'The soup has ten seconds of cooking time remaining.',
        'An empty plate separates the two onions on the bench.',
        'The order shown at the top is still waiting to be filled.',
    ],
    ('descriptive', 'trajectory'): [
        'Earlier in the round, you placed an onion on this worktop.',
        'A tomato was collected by the other cook on the previous turn.',
        'The last order was handed in before the timer reached zero.',
        'Your partner has just come back from the serving point.',
        'You have been waiting beside the stove for six steps.',
        'The cook in the blue hat took the dish off that counter.',
        'We completed three deliveries during the previous shift.',
        'No ingredients were collected during your last trip.',
        'You spent the previous turn standing behind me.',
        'A bowl changed hands when you interacted with the bench.',
        'The soup was delivered while I was holding the onion.',
        'On the last move you turned to face the lower wall.',
        'Our previous game lasted exactly two minutes.',
        'You passed the cooking station twice on your way back.',
        'The last action added a tomato to the upper pot.',
        'You had already left the stove when I arrived.',
        'I saw you move the plate from one counter to the other.',
        'You ended the round with a bowl in your hands.',
        'The scoreboard gained two points on that delivery.',
        'The partner crossed the middle aisle on the preceding turn.',
    ],
}

rows = []
for (speech, grounding), texts in GROUPS.items():
    for index, text in enumerate(texts):
        rows.append(dict(text=text, speech_act=speech, grounding=grounding,
            group_id=f'root_authored_{speech}_{grounding}_{index}',
            source='new_synthetic_seed_v3', human_data=False))
target = Path(__file__).resolve().parents[1] / 'data/synthetic_feedback_v1/v3_external_seeds.json'
if target.exists():
    raise SystemExit('Refusing to overwrite synthetic seeds')
target.write_text(json.dumps(rows, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(json.dumps({'rows': len(rows), 'path': str(target), 'human_data': False}))
