"""Supervise a PPO policy on a short expert action prefix.

This is a small diagnostic warm-start tool: it keeps the RLlib PPO checkpoint
format, but applies a supervised cross-entropy update to one PPO policy's logits
on states generated by a deterministic action prior.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

import dill
import numpy as np
import tensorflow as tf

from durf.baseline.action_prior import (
    COUNTER_ONION_TO_POT_TOP,
    prefix_action_indices,
)
from durf.baseline.runtime import AGENT_ROOT, make_direct_multi_env, resolve_agent_dir
from human_aware_rl.rllib.rllib import load_trainer, save_trainer
from overcooked_ai_py.mdp.actions import Action


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_ROOT = REPO_ROOT / "outputs" / "prefix_supervision"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--agent", required=True)
    parser.add_argument("--layout", required=True)
    parser.add_argument("--agent-name", required=True)
    parser.add_argument("--prior", default=COUNTER_ONION_TO_POT_TOP)
    parser.add_argument("--policy-id", default="ppo_0")
    parser.add_argument("--epochs", type=int, default=500)
    parser.add_argument("--learning-rate", type=float, default=1e-4)
    parser.add_argument("--repeat", type=int, default=128)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--num-seeds",
        type=int,
        default=1,
        help="Number of consecutive environment seeds used to collect prefix examples.",
    )
    parser.add_argument(
        "--train-scope",
        choices=("all", "logits"),
        default="all",
        help="Which PPO model variables to update. 'logits' only updates the action output head.",
    )
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def load_params_for_agent(agent_dir: Path) -> dict:
    config_path = agent_dir.parent / "config.pkl"
    if not config_path.exists():
        raise FileNotFoundError(f"Training config not found: {config_path}")
    with config_path.open("rb") as handle:
        return dill.load(handle)


def collect_prefix_examples(
    trainer,
    layout: str,
    prior: str,
    policy_id: str,
    seed: int,
    num_seeds: int,
) -> tuple[np.ndarray, np.ndarray]:
    dummy_env = trainer.env_creator(trainer.config["env_config"])
    featurize_fn = dummy_env._get_featurize_fn(policy_id)
    observations: list[np.ndarray] = []
    labels: list[int] = []
    stay = Action.ACTION_TO_INDEX[Action.STAY]

    for seed_offset in range(num_seeds):
        env = make_direct_multi_env(layout, seed + seed_offset)
        env.multi_reset()
        try:
            for action_index in prefix_action_indices(prior):
                state = env.base_env.state
                try:
                    obs_pair = featurize_fn(state, debug=False)
                except TypeError:
                    obs_pair = featurize_fn(state)
                observations.append(np.asarray(obs_pair[0], dtype=np.float32))
                labels.append(int(action_index))
                env.multi_step(action_index, stay)
        finally:
            env.close()
    return np.stack(observations), np.asarray(labels, dtype=np.int32)


def supervise_policy(
    trainer,
    policy_id: str,
    observations: np.ndarray,
    labels: np.ndarray,
    epochs: int,
    learning_rate: float,
    repeat: int,
    train_scope: str,
) -> tuple[list[float], list[str]]:
    policy = trainer.get_policy(policy_id)
    if policy is None:
        raise ValueError(f"Policy not found in trainer: {policy_id}")
    model = policy.model
    if not hasattr(model, "base_model"):
        raise TypeError(f"Policy model for {policy_id} has no base_model")

    x = np.repeat(observations, repeat, axis=0).astype(np.float32)
    y = np.repeat(labels, repeat, axis=0).astype(np.int32)
    losses: list[float] = []
    variables = list(model.variables())
    if train_scope == "logits":
        train_variables = [
            variable for variable in variables if f"{policy_id}/dense_3/" in variable.name
        ]
    else:
        train_variables = variables
    if not train_variables:
        variable_names = ", ".join(variable.name for variable in variables)
        raise ValueError(
            f"No variables selected by train scope {train_scope!r}. "
            f"Available variables: {variable_names}"
        )

    # RLlib 2.2 builds this custom PPO model in TF1 graph mode.  Train the
    # existing policy graph directly so the saved checkpoint contains the update.
    session = policy._sess
    with session.graph.as_default():
        obs_ph = model.base_model.inputs[0]
        logits = model.base_model.outputs[0]
        label_ph = tf.compat.v1.placeholder(tf.int32, shape=[None], name="prefix_labels")
        loss = tf.reduce_mean(
            tf.nn.sparse_softmax_cross_entropy_with_logits(
                labels=label_ph,
                logits=logits,
            )
        )
        optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate)
        train_op = optimizer.minimize(
            loss,
            var_list=train_variables,
        )
        uninitialized = [
            variable
            for variable in tf.compat.v1.global_variables()
            if not session.run(tf.compat.v1.is_variable_initialized(variable))
        ]
        if uninitialized:
            session.run(tf.compat.v1.variables_initializer(uninitialized))

        for _ in range(epochs):
            loss_value, _ = session.run(
                [loss, train_op],
                feed_dict={
                    obs_ph: x,
                    label_ph: y,
                },
            )
            losses.append(float(loss_value))
    return losses, [variable.name for variable in train_variables]


def install_supervised_agent(run_dir: Path, checkpoint_path: Path, agent_name: str, overwrite: bool) -> Path:
    install_root = AGENT_ROOT / agent_name
    agent_dir = install_root / "agent"
    if agent_dir.exists():
        if not overwrite:
            raise FileExistsError(f"Agent already exists: {agent_dir}")
        shutil.rmtree(agent_dir)
    install_root.mkdir(parents=True, exist_ok=True)
    shutil.copy2(run_dir / "config.pkl", install_root / "config.pkl")
    agent_dir.mkdir(parents=True, exist_ok=True)
    shutil.copytree(checkpoint_path, agent_dir / checkpoint_path.name)
    return agent_dir


def main() -> int:
    args = parse_args()
    agent_dir = resolve_agent_dir(args.agent)
    params = load_params_for_agent(agent_dir)
    trainer = load_trainer(str(agent_dir))
    try:
        observations, labels = collect_prefix_examples(
            trainer,
            args.layout,
            args.prior,
            args.policy_id,
            args.seed,
            args.num_seeds,
        )
        losses, trained_variables = supervise_policy(
            trainer,
            args.policy_id,
            observations,
            labels,
            args.epochs,
            args.learning_rate,
            args.repeat,
            args.train_scope,
        )
        run_dir = OUTPUT_ROOT / args.agent_name
        run_dir.mkdir(parents=True, exist_ok=True)
        checkpoint_path = Path(save_trainer(trainer, params, str(run_dir)))
        installed = install_supervised_agent(
            run_dir,
            checkpoint_path,
            args.agent_name,
            args.overwrite,
        )
        print(f"Examples: {len(labels)}")
        print(f"Seed range: {args.seed}..{args.seed + args.num_seeds - 1}")
        print(f"Labels: {labels.tolist()}")
        print(f"Train scope: {args.train_scope}")
        print(f"Trained variables: {trained_variables}")
        print(f"Initial loss: {losses[0]:.6f}")
        print(f"Final loss: {losses[-1]:.6f}")
        print(f"Saved checkpoint: {checkpoint_path}")
        print(f"Installed agent: {installed}")
    finally:
        trainer.stop()
    return 0


if __name__ == "__main__":
    sys.exit(main())
